# Generated by Django 6.0.7 on 2026-07-19 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='hero/')),
                ('cta_primary_text', models.CharField(default='Explore Our Menu', max_length=50)),
                ('cta_primary_url', models.CharField(default='/menu/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Order on WhatsApp', max_length=50)),
                ('cta_secondary_url', models.CharField(default='https://wa.me/254119000999', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['ordering', 'created_at'],
            },
        ),
    ]
