# Generated by Django 6.0.7 on 2026-07-19 15:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_heroslide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='badge',
            field=models.CharField(blank=True, help_text="Small badge above headline — e.g. 'Halal Certified · 100%% Alcohol-Free'", max_length=150),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_secondary_text',
            field=models.CharField(blank=True, default='Order on WhatsApp', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_secondary_url',
            field=models.CharField(blank=True, default='https://wa.me/254119000999', max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True, help_text='Optional body text shown beneath the headline.'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Background photo. Leave blank for the elegant pattern background.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Gold italic sub-headline — e.g. 'Served With Excellence.'", max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(help_text="Main headline — e.g. 'Crafted With Love.'", max_length=150),
        ),
    ]
