# Generated by Django 6.0.7 on 2026-07-19 07:46

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('bg_color', models.CharField(default='#3E2723', help_text='CSS color for background', max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default="KAWA'S Café", max_length=100)),
                ('site_tagline', models.CharField(default='Crafted With Love', max_length=255)),
                ('site_description', models.TextField(default='Premium Specialty Coffee, Artisan Desserts & Halal Dining in Nyali, Mombasa')),
                ('phone', models.CharField(default='+254 119 000 999', max_length=20)),
                ('whatsapp', models.CharField(default='254119000999', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(default='Mount Kenya Road, Nyali, Mombasa, Kenya', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/kawa_ske')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/kawa_ske')),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com/@kawa_ske')),
                ('google_maps_url', models.URLField(blank=True, default='https://maps.google.com/?q=Kawa%27s+Nyali+Mombasa')),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps iframe embed code')),
                ('meta_title', models.CharField(default="KAWA'S Café — Premium Coffee & Desserts in Nyali, Mombasa", max_length=70)),
                ('meta_description', models.CharField(default="KAWA'S Café offers premium specialty coffee, artisan matcha, halal desserts, and a luxury café experience in Nyali, Mombasa, Kenya.", max_length=160)),
                ('footer_about', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('footer_tagline', models.CharField(default='Crafted With Love. Served With Excellence.', max_length=255)),
                ('show_prayer_times', models.BooleanField(default=False)),
                ('online_ordering_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
